# Generated by Django 4.2.14 on 2024-07-15 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название', max_length=130, null=True, verbose_name='Название')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Текущий баланс на счете', max_digits=12, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Банковский счет',
                'verbose_name_plural': 'Банковские счета',
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма транзакции', max_digits=12, verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('account', models.ForeignKey(help_text='Уникальный идентификатор', on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='transactions.bankaccount', verbose_name='Идентификатор счёта')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'db_table': 'operations',
            },
        ),
    ]
